package com.krgamestudios.toy;

enum TokenType {
	//single character tokens
	LEFT_PAREN, RIGHT_PAREN,
	LEFT_BRACKET, RIGHT_BRACKET,
	LEFT_BRACE, RIGHT_BRACE,
	STAR, SLASH, MODULUS, SEMICOLON, COMMA, QUOTE,

	//one or two character tokens
	EQUAL, EQUAL_EQUAL, EQUAL_GTHAN,
	LTHAN, LTHAN_EQUAL,
	GTHAN, GTHAN_EQUAL,
	BANG, BANG_EQUAL,
	AND, AND_AND,
	OR, OR_OR,
	PLUS, PLUS_PLUS,
	MINUS, MINUS_MINUS,
	DOT, DOT_DOT,

	//literals
	IDENTIFIER, STRING, NUMBER,

	//keywords
	BREAK, CLASS, CONTINUE, ELSE, FALSE, FOR, /* FOREACH, */ FUNCTION,
	IF, LOG, MODULE, RECURSE, RETURN, THIS, TRUE, UNDEFINED, USE, VAR,
	WHILE,

	//EOF
	EOF
}